name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/fsq-node-backend:latest .

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fsq-node-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/fsq-node-backend:latest
            docker stop fsq-node-backend || true
            docker rm fsq-node-backend || true
            docker run -d --name fsq-node-backend \
              -p 5000:5000 \
              -e FSQ_API_KEY=${{ secrets.FSQ_API_KEY }} \
              -e FSQ_BASE_URL=${{ secrets.FSQ_BASE_URL }} \
              -e PORT=${{ secrets.PORT }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/fsq-node-backend:latest
